DEBUG 2024-07-11 14:21:19.193 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-07-11 14:21:19.193 UTC: 	 Running on: Linux cms-fe01.rcac.purdue.edu 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-07-11 14:21:19.193 UTC: 	 Executing command: 'status'
DEBUG 2024-07-11 14:21:19.194 UTC: 	 Found CRAB cache file /home/kaur214/.crab3
ERROR 2024-07-11 14:21:19.195 UTC: 	 Cannot find .requestcache file in CRAB project directory /depot/cms/private/users/kaur214/analysis_facility/limits/ZPrimeCombine/submission/crab_projects/crab_limits_combB_6_20240710_145959
ERROR 2024-07-11 14:21:19.195 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 684, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 525, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /depot/cms/private/users/kaur214/analysis_facility/limits/ZPrimeCombine/submission/crab_projects/crab_limits_combB_6_20240710_145959
INFO 2024-07-11 14:21:19.197 UTC: 	 Log file is /depot/cms/private/users/kaur214/analysis_facility/limits/ZPrimeCombine/submission/crab.log
DEBUG 2024-07-11 14:47:06.517 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-07-11 14:47:06.517 UTC: 	 Running on: Linux cms-fe01.rcac.purdue.edu 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-07-11 14:47:06.517 UTC: 	 Executing command: 'status'
DEBUG 2024-07-11 14:47:06.517 UTC: 	 Found CRAB cache file /home/kaur214/.crab3
ERROR 2024-07-11 14:47:06.519 UTC: 	 Cannot find .requestcache file in CRAB project directory /depot/cms/private/users/kaur214/analysis_facility/limits/ZPrimeCombine/submission/crab_projects/crab_limits_crab_6_20240711_104230
ERROR 2024-07-11 14:47:06.519 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 684, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 531, in loadLocalCache
    raise ex
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 525, in loadLocalCache
    self.cachedinfo, self.logfile = loadCache(self.requestarea, self.logger)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/ClientUtilities.py", line 445, in loadCache
    raise CachefileNotFoundException(msg)
CRABClient.ClientExceptions.CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /depot/cms/private/users/kaur214/analysis_facility/limits/ZPrimeCombine/submission/crab_projects/crab_limits_crab_6_20240711_104230
INFO 2024-07-11 14:47:06.521 UTC: 	 Log file is /depot/cms/private/users/kaur214/analysis_facility/limits/ZPrimeCombine/submission/crab.log
DEBUG 2024-07-11 16:40:30.477 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-07-11 16:40:30.477 UTC: 	 Running on: Linux cms-fe01.rcac.purdue.edu 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-07-11 16:40:30.477 UTC: 	 Executing command: 'kill'
DEBUG 2024-07-11 16:40:30.478 UTC: 	 Found CRAB cache file /home/kaur214/.crab3
ERROR 2024-07-11 16:40:30.478 UTC: 	 Error: Please indicate the CRAB project directory with --dir=<project-directory>.
ERROR 2024-07-11 16:40:30.478 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 676, in validateOptions
    raise ex
CRABClient.ClientExceptions.MissingOptionException: [91mError[0m: Please indicate the CRAB project directory with --dir=<project-directory>.
INFO 2024-07-11 16:40:30.479 UTC: 	 Log file is /depot/cms/private/users/kaur214/analysis_facility/limits/ZPrimeCombine/submission/crab.log
DEBUG 2024-07-11 16:41:16.484 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-07-11 16:41:16.484 UTC: 	 Running on: Linux cms-fe01.rcac.purdue.edu 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-07-11 16:41:16.485 UTC: 	 Executing command: 'status'
DEBUG 2024-07-11 16:41:16.485 UTC: 	 Found CRAB cache file /home/kaur214/.crab3
ERROR 2024-07-11 16:41:16.486 UTC: 	 Error: crab_projects/crab_li is not a valid CRAB project directory.
ERROR 2024-07-11 16:41:16.486 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_projects/crab_li is not a valid CRAB project directory.
INFO 2024-07-11 16:41:16.488 UTC: 	 Log file is /depot/cms/private/users/kaur214/analysis_facility/limits/ZPrimeCombine/submission/crab.log
DEBUG 2024-07-11 17:45:54.619 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-07-11 17:45:54.620 UTC: 	 Running on: Linux cms-fe01.rcac.purdue.edu 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-07-11 17:45:54.620 UTC: 	 Executing command: 'status'
DEBUG 2024-07-11 17:45:54.620 UTC: 	 Found CRAB cache file /home/kaur214/.crab3
ERROR 2024-07-11 17:45:54.621 UTC: 	 Error: submission/crab_projects/crab_limits_crab_10_20240711_132009/ is not a valid CRAB project directory.
ERROR 2024-07-11 17:45:54.621 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: submission/crab_projects/crab_limits_crab_10_20240711_132009/ is not a valid CRAB project directory.
INFO 2024-07-11 17:45:54.623 UTC: 	 Log file is /depot/cms/private/users/kaur214/analysis_facility/limits/ZPrimeCombine/submission/crab.log
